
your_ip: "$YOUR_IP"
your_proxy_http_proxy: "http://172.17.0.1:10809"
your_proxy_no_proxy: "localhost,127.0.0.1,{{ matrix_domain }},.{{ matrix_domain }},matrix-synapse,matrix-authentication-service,matrix-postgres,matrix-exim-relay,172.16.0.0/12"

matrix_domain: "$DOMAIN"                                  # ВСТАВИТЬ свой ОСНОВНОЙ ДОМЕН
matrix_server_fqn_matrix: "$DOMAIN_MATRIX"                # ВСТАВИТЬ свой домен для MATRIX
coturn_hostname: "$DOMAIN_COTURN"                         # ВСТАВИТЬ свой домен для COTURN (старые звонки 1-на-1)
matrix_element_call_hostname: "$DOMAIN_CALL"              # ВСТАВИТЬ свой домен для Element Call (современные звонки + групповые)
ntfy_hostname: "$DOMAIN_NTFY"                             # ВСТАВИТЬ свой домен для NTFY (уведомления)
matrix_element_admin_hostname: "$DOMAIN_ADMIN_PANEL"      # ВСТАВИТЬ свой домен для Element Admin
matrix_server_fqn_element: "$DOMAIN_WEB_CLIENT"           # ВСТАВИТЬ свой домен для Web CLient (Element Web)


# Проверка версии плейбука
matrix_playbook_migration_validated_version: v2026.04.24.0

# Это заставит matrix-клиенты искать настройки по адресу *ваш домен*/.well-known/matrix/client
matrix_well_known_matrix_client_enabled: true

# Для федерации
matrix_static_files_container_labels_base_domain_enabled: true

# обратный прокси - traefik - дефолт для этого ansible playbook
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
traefik_config_certificatesResolvers_acme_email: '$ADMIN_EMAIL'   # ВСТАВИТЬ EMAIL ДЛЯ ИНФОРМАЦИИ ОБ SSL СЕРТИФИКАТОВ ОТ  LET'S ENCRYPT

# Настройки для Synapse
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: '$GENERIC_SECRET'           # ВСТАВИТЬ КАКОЙ-ТО СЕКРЕТНЫЙ КЛЮЧ (для матрикс-сервера)

# Глобальный таймаут Ansible (время ожидания ответа от системы)
# Время, которое дается systemd для перезапуска сервисов (секунды)
devture_systemd_service_manager_up_verification_delay_seconds: 600
# Увеличиваем таймаут запуска в самом systemd (в секундах)
matrix_synapse_systemd_service_specific_options: |
  TimeoutStartSec=600
# Настройки для Element Admin (часто падает из-за ещё не работающих зависимостей)
matrix_element_admin_systemd_service_specific_options: |
  TimeoutStartSec=300
  TimeoutStopSec=60

postgres_connection_password: '$DB_PASSWORD'                      # ВСТАВИТЬ КАКОЙ-ТО ПАРОЛЬ ДЛЯ БД

# (Если у вас сервер - Synapse и не используется MAS, то настраиваем это на true)
# true Включает возможность самостоятельной регистрации
matrix_synapse_enable_registration: false
# Капча (требует доп. настройки поставщика капчи)
matrix_synapse_enable_registration_captcha: false
# Разрешает регистрационные токены Synapse (у MAS свои токены и настройка для них)
matrix_synapse_registration_requires_token: false
# Ограничение на размер скачиваемых файлов (число в мегабайтах, по дефолту было 50мб)
matrix_synapse_max_upload_size_mb: 2048

# Поиск пользователей

# Определяет, кого Synapse вообще включает в поисковый индекс.
# false: В поиске появятся только те пользователи,
#    с которыми у вас есть общие комнаты.
# true: В поиске будут доступны все зарегистрированные пользователи вашего сервера,
#    даже если вы с ними никак не пересекались.
matrix_synapse_user_directory_search_all_users: true
# Влияет на ранжирование (порядок выдачи) в результатах поиска.
# false: Результаты сортируются по релевантности (совпадению букв),
#    без приоритета места регистрации.
# true: Ваши «местные» пользователи (зарегистрированные на @ваш-домен.com)
#    будут всегда отображаться вверху списка, даже если есть более точные совпадения с пользователями
#    из других серверов (федерации).
matrix_synapse_user_directory_prefer_local_users: true
# Фильтр-отсечка для внешней федерации.
# false: В поиске могут появляться пользователи с других серверов
#    (если ваш сервер о них знает, например, через общие комнаты).
# true: Полностью запрещает показ любых пользователей в поиске c других серверов.
#    Вы будете видеть только тех, кто зарегистрирован лично на вашем сервере.
matrix_synapse_user_directory_exclude_remote_users: false

# Срок жизни медиа-файлов ВАШЕГО сервера от ваших пользователей (пусто = файлы живут вечно)
matrix_synapse_media_retention_local_media_lifetime:
# Срок жизни медиа-файлов со СТОРОННИХ серверов от других пользователей.
# Настройка: 7 дней - 7d, 2 недели - 2w, 1 месяц - 1m, 1 год - 1y
matrix_synapse_media_retention_remote_media_lifetime: 2w

# ntfy для уведомлений
ntfy_enabled: true
# Для ntfy Настройки прокси и DNS
ntfy_container_extra_arguments:
  - "--env"
  - "http_proxy={{ your_proxy_http_proxy }}"
  - "--env"
  - "https_proxy={{ your_proxy_http_proxy }}"
  - "--env"
  - "no_proxy={{ your_proxy_no_proxy }}"
  - "--dns"
  - "127.0.0.11"

# Явно говорим synapse где искать локальный ntfy
matrix_synapse_container_extra_hosts:
  - "{{ ntfy_hostname }}:host-gateway"

# Для Synapse настройки прокси, DNS и уведомления
matrix_synapse_container_extra_arguments:
  - "--add-host={{ ntfy_hostname }}:host-gateway"
  - "--env"
  - "http_proxy={{ your_proxy_http_proxy }}"
  - "--env"
  - "https_proxy={{ your_proxy_http_proxy }}"
  - "--env"
  # Без прокси: все локальные адреса, ваши домены,
  #  матрикс-контейнеры, которые могут общаться между собой по https (например Synapse <-> MAS) и все локальные адреса докера
  - "no_proxy={{ your_proxy_no_proxy }}"
  # Внутренний DNS докера
  - "--dns"
  - "127.0.0.11"

# Дополнительные настройки Synapse
matrix_synapse_configuration_extension_yaml: |
  #Список комнат, в которые пользователь попадет сразу после регистрации
  #auto_join_rooms:
  #  - "#your-room:your-server.com"
  #белые списки Synapse чтобы он мог обращаться к другим сервисам по локальному ip (важно для работающих уведомлений)
  ip_range_whitelist:
    - "172.16.0.0/12"
    - "10.0.0.0/8"
    - "127.0.0.0/8"
    - "192.168.0.0/16"

# Настраиваем ограничения сервера synapse чтобы не нагружать процессор огромными matrix-комнатами
matrix_synapse_limit_remote_rooms_enabled: true
matrix_synapse_limit_remote_rooms_complexity: 15.0
matrix_synapse_limit_remote_rooms_complexity_error: "Наш сервер не может подключаться к таким большим/тяжелым комнатам."
matrix_synapse_limit_remote_rooms_admins_can_join: false
# Если false - Убирает опросы online/offline - важно при федерации, иначе CPU будет постоянно нагружен
matrix_synapse_presence_enabled: false

# Звонки p2p
coturn_enabled: true
coturn_turn_external_ip_addresses: ["{{ your_ip }}"]
coturn_turn_static_auth_secret: "$COTURN_SECRET"                   # ВСТАВИТЬ КАКОЙ-ТО СЕКРЕТНЫЙ КЛЮЧ (для звонков через coturn)
coturn_turn_udp_min_port: 49152
coturn_turn_udp_max_port: 49652

# Групповые звонки через Element Call (livekit)
matrix_rtc_enabled: true
matrix_element_call_enabled: true
matrix_client_element_jitsi_preferred: false
matrix_client_element_voip_conference_type: "livekit"
# Принуждаем LiveKit работать корректно через TCP, если UDP блокируют
livekit_server_config_turn_external_tls: true
livekit_server_configuration_extension_yaml: |
  rtc:
    force_tcp: true

# Если сервер не знает своего внешнего IP, пакеты застревают
livekit_rtc_use_external_ip: true
livekit_rtc_external_ip: "{{ your_ip }}"

# Админка Ketesa (бывший synapse-admin от etke.cc ( доступ: *ваш хост*/ketesa )
matrix_ketesa_enabled: true
# Админка Element Admin
matrix_element_admin_enabled: true


# Настройка Matrix Authentication Service (MAS)
matrix_authentication_service_enabled: true
matrix_authentication_service_config_secrets_encryption: "$MAS_ENC_KEY"     # ВСТАВИТЬ КАКОЙ-ТО ПАРОЛЬ для MAS
# Если вы переносите авторизацию с обычного способа на MAS, то нужно поставить true
matrix_authentication_service_migration_in_progress: false

# Позволяет пользователям логиниться, используя email вместо username (удобно для сброса, но нужно настраивать отдельно)
matrix_authentication_service_config_account_login_with_email_allowed: false
# Включаем возможность регистрации по паролю, а не только через сторонних auth-поставщиков
matrix_authentication_service_config_account_password_registration_enabled: true
# Требовать токен для регистрации
matrix_authentication_service_config_account_registration_token_required: true
# Требовать email при регистрации
matrix_authentication_service_config_account_password_registration_email_required: false
# Позволяет пользователям самостоятельно Сбрасывать пароль по почте (нужно настроить работу с почтой на вашем сервере)
matrix_authentication_service_config_account_password_recovery_enabled: false
# Позволяет пользователям самостоятельно Менять пароль в настройках
matrix_authentication_service_config_account_password_change_allowed: true

# Настройки прокси для MAS
matrix_authentication_service_container_extra_arguments:
  - "--env"
  - "http_proxy={{ your_proxy_http_proxy }}"
  - "--env"
  - "https_proxy={{ your_proxy_http_proxy }}"
  - "--env"
  # Без прокси: все локальные адреса, ваши домены,
  #  матрикс-контейнеры, которые могут общаться между собой по https (например Synapse <-> MAS) и все локальные адреса докера
  - "no_proxy={{ your_proxy_no_proxy }}"
  # Внутренний DNS докера
  - "--dns"
  - "127.0.0.11"


# Web-client Element
matrix_client_element_enabled: true
# Стандартный телефонный код (+7)
matrix_client_element_default_country_code: "RU"
# Темы оформления из репозитория
matrix_client_element_themes_enabled: true
matrix_client_element_themes_repository_url: "https://github.com/aaronraimist/element-themes"
# Включение сторонних тем по ссылке
matrix_client_element_setting_defaults_custom_themes_enabled: true
matrix_client_element_configuration_extension_json: |
  {
    "csp": {
      "style-src": ["'self'", "'unsafe-inline'", "https://*"],
      "img-src": ["'self'", "data:", "blob:", "https://*"],
      "connect-src": ["'self'", "https://*", "wss://*"]
    }
  }
